name: Validate Against Manifests

on:
  pull_request:
    paths:
      - 'magica/resource/download/asset/master/resource/**'
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  validate-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/base
          CHANGED=$(git diff --diff-filter=AM --name-only origin/base...${{ github.sha }} magica/resource/download/asset/master/resource || true)
          REL_PATHS=$(echo "$CHANGED" | sed -e "s#^magica/resource/download/asset/master/resource/##")
          {
            echo 'files<<EOF'
            printf "%s\n" $REL_PATHS
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Download & parse manifests
        run: |
          mkdir -p manifests
          for name in asset_main asset_fullvoice asset_voice asset_movieall_high; do
            curl -sSL "${MANIFEST_BASE}${name}.json.gz" > manifests/"${name}.json"
          done
          jq -r '.[].path' manifests/*.json | sort -u > all_paths.txt
        env:
          MANIFEST_BASE: ${{ secrets.MANIFEST_BASE }}

      - name: Validate changed files
        id: validate
        run: |
          missing=""
          NEWLINE=$'\n'
          for file in ${{ steps.changed.outputs.files }}; do
            [ -z "$file" ] && continue
            if ! grep -xFq "$file" all_paths.txt; then
              url="https://github.com/${{ github.repository }}/blob/${{ github.sha }}/magica/resource/download/asset/master/resource/$file"
              missing="$missing$NEWLINE - [$file]($url)"
            fi
          done
          if [ -n "$missing" ]; then
            {
              echo 'MISSING_FILES<<EOF'
              echo $missing
              echo 'EOF'
            } >> $GITHUB_ENV
            exit 1
          fi

      - name: Post comment on PR for missing files
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const missing = process.env.MISSING_FILES;
            if (missing) {
              const body = `## :warning: Asset files not listed in any manifest:\n<details><summary>File list</summary>\n\n${missing}\n\n</details>\n`;
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            }
